apiVersion: apps/v1
kind: Deployment

metadata:
  name: vulnerable-flask-app
  namespace: devsecops

spec:
  replicas: 4

  selector:
    matchLabels:
      app: vulnerable-flask-app

  template:
    metadata:
      labels:
        app: vulnerable-flask-app

    spec:

      # Spread Flask pods across different worker nodes
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: vulnerable-flask-app

      containers:
        - name: flask-app

          image: 266092630927.dkr.ecr.ap-south-1.amazonaws.com/vulnerable-flask-app:1.0

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          envFrom:
            - secretRef:
                name: postgres-secret

          # Check whether the application is alive
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          # Only send traffic when the application is ready
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "513Mi"