apiVersion: apps/v1
kind: Deployment

metadata:
  name: vulnerable-flask-app
  namespace: devsecops

spec:

  replicas: 3

  selector:
    matchLabels:
      app: vulnerable-flask-app

  template:

    metadata:
      labels:
        app: vulnerable-flask-app

    spec:

      containers:

        - name: flask-app

          # GitHub Actions will replace IMAGE_PLACEHOLDER
          # with the exact ECR image and Git commit SHA.
          image: IMAGE_PLACEHOLDER

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          envFrom:
            - secretRef:
                name: postgres-secret

          resources:

            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "513Mi"
