apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devsecops
type: Opaque
stringData:
  DB_HOST: "10.0.20.146"
  DB_NAME: "devsecops_db"
  DB_USER: "devsecops"
  DB_PASSWORD: "CHANGE_ME_STRONG_PASSWORD"
  DB_PORT: "5432"
  
#  PGPASSWORD='CHANGE_ME_STRONG_PASSWORD' psql -h 10.0.20.117 -p 5432 -U devsecops   -d devsecops_db
