apiVersion: v1
kind: Service

metadata:
  name: vulnerable-flask-service
  namespace: devsecops

spec:

  type: LoadBalancer

  selector:
    app: vulnerable-flask-app

  ports:

    - protocol: TCP

      port: 80

      targetPort: 5000
